import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { David_Libre } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ScrollAnimationProvider } from "./components/ScrollAnimationProvider";
import { PageTransition } from "./components/PageTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const davidLibre = David_Libre({
  variable: "--font-david-libre",
  subsets: ["hebrew", "latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${davidLibre.variable} antialiased`}
      >
        <ScrollAnimationProvider>
          <Navbar />
          <PageTransition>
            {children}
            <Footer />
          </PageTransition>
        </ScrollAnimationProvider>
      </body>
    </html>
  );
}
